# Generated by Django 4.1.7 on 2023-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_alter_acessorio_options_alter_cor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(related_name='acessórios', to='garagem.acessorio'),
        ),
    ]
